### ISSUE TITLE
Not allowing me to log in

### ISSUE THREAD

**Issue by evelynf** [pwnall/igor#177]
It asks me to verify my email, but it never sent me an email to do so. Also I have 6.006 as a class on this too. Maybe that's why it does so?

**Comment by pwnall** [comment]
There's very little we can do for this, from a code perspective. Confirmation e-mails are brittle, and could be avoided if we could read MIT certificates. Unfortunately, doing that at the moment is quite difficult.

If IS&T would create an OAuth endpoint that'd work with certificates, we could just implement OAuth. Until that happens, I'm afraid we'll stick to handling lost e-mail confirmations via tech support.
