### ISSUE TITLE
crash on production site

### ISSUE THREAD

**Issue by ilebedev** [pwnall/igor#188]
While analyses do seem to be running to completion, opening any analysis view for s04 Lab 4 throws a 500. Other labs seem to be intact.

This came to be after an analyzer update and 2 TAs simultaneously messing with the queue.

https://funprog.net/6.S04/analyses/418

I can investigate if you forward me a crash log

**Comment by ilebedev** [comment]
This in fact affects new analyses for new submissions, including ones for other labs.

**Comment by ilebedev** [comment]
Tentative observation: only staff submissions are affected
Unaffected student analysis: https://funprog.net/6.S04/analyses/504

**Comment by pwnall** [comment]
I think this was fixed in ea94abe4073b32aaa42080db4f82991d25584c98.
