### ISSUE TITLE
Grades blank

### ISSUE THREAD

**Issue by edahlseng** [pwnall/igor#189]
When viewing the grades page, it is blank

**Comment by pwnall** [comment]
Server: alg.csail.mit.edu

Can you please try again? I think you should be seeing grades for PS1.

**Comment by edahlseng** [comment]
It works now, and worked last night.  But yesterday early evening it showed only a blank page, even after refreshing multiple times.  This was after the announcement that grades were released, but perhaps something wasn't fully ready?

**Comment by pwnall** [comment]
I'm sorry you weren't seeing your grades, and I thank you very much for the report!

Sadly, I don't have much to go off right now. If this happens again, please use the "Report Issue" link again to report a new issue. Hopefully, I'll see it early enough to be able to debug things.
