### ISSUE TITLE
Allow "release grades" to be avoided for some assignments

### ISSUE THREAD

**Issue by achlipala** [pwnall/igor#211]
With the 6.009 model, we want students to be able to see their grades as soon as they are determined, say right after a staff member does a checkoff.  Could we avoid the need to release grades for assignments that follow this mode?  Otherwise, a staff member needs to be clicking "release grades" daily to avoid student complaints!

**Comment by achlipala** [comment]
Learning more by scientific induction, it looks like grades stay released once released, so that updates then appear immediately.  Is that right?  If so, then all we need to do is click the button once, which is fine, so maybe this issue is invalid.

**Comment by pwnall** [comment]
@achlipala You are correct, grades stay  released once they are released. If you want students to see their grades all the time, you can release them right after you publish the assignment. Introducing an option for this would still require at least 1 click, so I think using the `Release grades` button is a quick solution.
